<a href="https://colab.research.google.com/github/vsrnitp/twitter-data/blob/main/Rudra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install tweet-preprocessor

In [ ]:
import preprocessor as p
import numpy as np 
import pandas as pd 

In [ ]:
pip install emoji

     |████████████████████████████████| 133kB 4.2MB/s 


In [ ]:
import emoji
print(emoji.emojize('Python is :thumbs_up:'))

Python is 👍


In [ ]:
import keras

In [ ]:
from sklearn.model_selection import train_test_split
import tensorflow as tf
from keras.models import Sequential
from keras.layers.recurrent import LSTM, GRU,SimpleRNN
from keras.layers.core import Dense, Activation, Dropout
from keras.layers.embeddings import Embedding
from keras.layers.normalization import BatchNormalization
from keras.utils import np_utils
from sklearn import preprocessing, decomposition, model_selection, metrics, pipeline
from keras.layers import GlobalMaxPooling1D, Conv1D, MaxPooling1D, Flatten, Bidirectional, SpatialDropout1D
from keras.preprocessing import sequence, text
from keras.callbacks import EarlyStopping
from sklearn.preprocessing import LabelEncoder,OneHotEncoder
import plotly.graph_objects as go
import plotly.express as px
from tensorflow.keras.layers import Dense, Input
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.models import Model
from tensorflow.keras.callbacks import ModelCheckpoint

In [ ]:
pip install transformers

     |████████████████████████████████| 1.8MB 5.3MB/s 
     |████████████████████████████████| 890kB 38.9MB/s 
     |████████████████████████████████| 3.2MB 46.2MB/s 
  Created wheel for sacremoses: filename=sacremoses-0.0.43-cp36-none-any.whl size=893261 sha256=51411ca6b7b62fda5883d4c60c8b496db11c5a1385fc21cc02f3520f9f3da017
  Stored in directory: /root/.cache/pip/wheels/29/3c/fd/7ce5c3f0666dab31a50123635e6fb5e19ceb42ce38d4e58f45
Successfully built sacremoses


In [ ]:
from transformers import TFAutoModel, AutoTokenizer
from tqdm.notebook import tqdm
from tokenizers import Tokenizer, models, pre_tokenizers, decoders, processors
from tqdm import tqdm

In [ ]:
test_dataset_url = 'https://raw.githubusercontent.com/vsrnitp/twitter-data/main/test.csv'
test_dataset = pd.read_csv(test_dataset_url,sep=",",header=None)

In [ ]:
test_dataset.head()

0                                                  1          2
0      textID                                               text  sentiment
1  f87dea47db  Last session of the day  http://twitpic.com/67ezh    neutral
2  96d74cb729   Shanghai is also really exciting (precisely -...   positive
3  eee518ae67  Recession hit Veronique Branquinho, she has to...   negative
4  01082688c6                                        happy bday!   positive

In [ ]:
train_dataset_url = 'https://raw.githubusercontent.com/vsrnitp/twitter-data/main/train.csv'
train_dataset = pd.read_csv(train_dataset_url,sep=",",header=None)

In [ ]:
train_dataset.head()

0  ...          3
0      textID  ...  sentiment
1  cb774db0d1  ...    neutral
2  549e992a42  ...   negative
3  088c60f138  ...   negative
4  9642c003ef  ...   negative

[5 rows x 4 columns]

In [ ]:
aspell_url = 'https://storage.googleapis.com/kagglesdsdata/datasets/1310/2365/aspell.txt?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=gcp-kaggle-com%40kaggle-161607.iam.gserviceaccount.com%2F20210220%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20210220T042106Z&X-Goog-Expires=259199&X-Goog-SignedHeaders=host&X-Goog-Signature=66d8c45b7ab67118f8156ef2977c0a5618a02afc3f3d4facd209ba62ee52134d647020655e562e31871d7c374187ed3fec8d941594ca91f7def91593ada392b5aadd1014d592968fbb59339044f4e91029de70cb9126d6bdfe148227493d5bea6e4dbbef2de9ec09753f91a6884ec515e42b582bf140a68374f38212392f27d84ed3c3fdb6426c32def559fd7b9d1532f4021ae73ec098ac1ef117609ca551bd51f5a9578d28084aee89182cf77d94de22dac8d347e212b64b732e6939dd6e7f5d3994fb9ab943cd28b72ced6bcb3f184bdb9fe151d6d8e04ddc97fb0093df9ca023884d8a3d4eabf0369833d2568904acb22afdbdaaac6917f43ec586069a2e'
misspell_data = pd.read_csv(aspell_url,sep=":",names=["correction","misspell"])

In [ ]:
misspell_data.head()

correction       misspell
0        Nevada         nevade
1  Presbyterian   presbyterian
2           RSX            rsx
3       Stephen        Steffen
4         Susan          susan

In [ ]:
misspell_data.misspell = misspell_data.misspell.str.strip()
misspell_data.misspell = misspell_data.misspell.str.split(" ")
misspell_data = misspell_data.explode("misspell").reset_index(drop=True)
misspell_data.drop_duplicates("misspell",inplace=True)
miss_corr = dict(zip(misspell_data.misspell, misspell_data.correction))

#Sample of the dict
{v:miss_corr[v] for v in [list(miss_corr.keys())[k] for k in range(20)]}

{'Steffen': 'Stephen',
 'abilitey': 'ability',
 'abouy': 'about',
 'absorbtion': 'absorption',
 'accidently': 'accidentally',
 'accomodate': 'accommodate',
 'acommadate': 'accommodate',
 'acord': 'accord',
 'adultry': 'adultery',
 'aggresive': 'aggressive',
 'alchohol': 'alcohol',
 'alchoholic': 'alcoholic',
 'allieve': 'alive',
 'alright': 'all_right',
 'aquantance': 'acquaintance',
 'equire': 'acquire',
 'nevade': 'Nevada',
 'presbyterian': 'Presbyterian',
 'rsx': 'RSX',
 'susan': 'Susan'}

In [ ]:
# for the time being i am not removing hashtags mentions and urls....
# will remove it later....
def misspelled_correction(val):
    for x in val.split(): 
        if x in miss_corr.keys(): 
            val = val.replace(x, miss_corr[x]) 
    return val

train_dataset["clean_content"] = train_dataset[1].apply(lambda x : misspelled_correction(str(x)))

In [ ]:
contractions_url = 'https://raw.githubusercontent.com/vsrnitp/twitter-data/main/contractions.csv'

In [ ]:
contractions = pd.read_csv(contractions_url)

In [ ]:
contractions.head()

Contraction  Meaning
0      'aight  alright
1       ain't   is not
2       amn't   am not
3      aren't  are not
4       can't   cannot

In [ ]:
cont_dic = dict(zip(contractions.Contraction, contractions.Meaning))

In [ ]:
def cont_to_meaning(val): 
  
    for x in val.split(): 
        if x in cont_dic.keys(): 
            val = val.replace(x, cont_dic[x]) 
    return val

In [ ]:
train_dataset.clean_content = train_dataset.clean_content.apply(lambda x : cont_to_meaning(str(x)))

In [ ]:
train_dataset.head()

0  ...                                   clean_content
0      textID  ...                                            text
1  cb774db0d1  ...             I`d have responded, if I were going
2  549e992a42  ...   Sooo SAD I will miss you here in San Diego!!!
3  088c60f138  ...                       my boss is bullying me...
4  9642c003ef  ...                  what interview! leave me alone

[5 rows x 5 columns]

In [ ]:
p.set_options(p.OPT.MENTION, p.OPT.URL)
p.clean("hello guys @alx #sport🔥 1245 https://github.com/s/preprocessor")

'hello guys #sport🔥 1245'

In [ ]:
train_dataset["clean_content"]=train_dataset.clean_content.apply(lambda x : p.clean(x))

In [ ]:
train_dataset.head()

0  ...                                  clean_content
0      textID  ...                                           text
1  cb774db0d1  ...            I`d have responded, if I were going
2  549e992a42  ...  Sooo SAD I will miss you here in San Diego!!!
3  088c60f138  ...                      my boss is bullying me...
4  9642c003ef  ...                 what interview! leave me alone

[5 rows x 5 columns]

In [ ]:
def punctuation(val): 
  
    punctuations = '''()-[]{};:'"\,<>./@#$%^&_~'''
  
    for x in val.lower(): 
        if x in punctuations: 
            val = val.replace(x, " ") 
    return val

In [ ]:
punctuation("test @ #ldfldlf??? !! ")

'test    ldfldlf??? !! '

In [ ]:
train_dataset.clean_content = train_dataset.clean_content.apply(lambda x : ' '.join(punctuation(emoji.demojize(x)).split()))

In [ ]:
train_dataset.head()

0  ...                                  clean_content
0      textID  ...                                           text
1  cb774db0d1  ...             I`d have responded if I were going
2  549e992a42  ...  Sooo SAD I will miss you here in San Diego!!!
3  088c60f138  ...                         my boss is bullying me
4  9642c003ef  ...                 what interview! leave me alone

[5 rows x 5 columns]

In [ ]:
def clean_text(val):
    val = misspelled_correction(val)
    val = cont_to_meaning(val)
    val = p.clean(val)
    val = ' '.join(punctuation(emoji.demojize(val)).split())
    
    return val

In [ ]:
clean_text("isn't 💡 adultry @ttt good bad ... ! ? ")

'is not light bulb adultery good bad ! ?'

In [ ]:
train_dataset = train_dataset[train_dataset.clean_content != ""]

In [ ]:
train_dataset[3].value_counts()

neutral      11116
positive      8582
negative      7781
sentiment        1
Name: 3, dtype: int64

In [ ]:
sent_to_id  = {"empty":0, "sadness":1,"enthusiasm":2,"neutral":3,"worry":4,
                        "surprise":5,"love":6,"fun":7,"hate":8,"happiness":9,"boredom":10,"relief":11,"anger":12,}

In [ ]:
base_sentiment = {"negative":0,"positive":1,"neutral":2}

In [ ]:
train_dataset["base_sentiment_id"] = train_dataset[3].map(base_sentiment)

In [ ]:
train_dataset.head(20)

0  ... base_sentiment_id
0       textID  ...               NaN
1   cb774db0d1  ...               2.0
2   549e992a42  ...               0.0
3   088c60f138  ...               0.0
4   9642c003ef  ...               0.0
5   358bd9e861  ...               0.0
6   28b57f3990  ...               2.0
7   6e0c6d75b1  ...               1.0
8   50e14c0bb8  ...               2.0
9   e050245fbd  ...               2.0
10  fc2cbefa9d  ...               1.0
11  2339a9b08b  ...               2.0
12  16fab9f95b  ...               1.0
13  74a76f6e0a  ...               0.0
14  04dd1d2e34  ...               0.0
15  bbe3cbf620  ...               2.0
16  8a939bfb59  ...               0.0
17  3440297f8b  ...               0.0
18  919fa93391  ...               0.0
19  af3fed7fc3  ...               0.0

[20 rows x 6 columns]

In [ ]:
from transformers import pipeline

In [ ]:
classifier = pipeline('sentiment-analysis')

In [ ]:
classifier(train_dataset[2][18])

[{'label': 'NEGATIVE', 'score': 0.9997228384017944}]

In [ ]:
pip install text2emotion

     |████████████████████████████████| 61kB 3.1MB/s 


In [ ]:
import text2emotion as te

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Unzipping corpora/wordnet.zip.


In [ ]:
text = "I was asked to sign a third party contract a week out from stay. If it wasn't an 8 person group that took a lot of wrangling I would have cancelled the booking straight away. Bathrooms - there are no stand alone bathrooms. Please consider this - you have to clear out the main bedroom to use that bathroom. Other option is you walk through a different bedroom to get to its en-suite. Signs all over the apartment - there are signs everywhere - some helpful - some telling you rules. Perhaps some people like this but It negatively affected our enjoyment of the accommodation. Stairs - lots of them - some had slightly bending wood which caused a minor injury."
text_love = "I love you!"
text1 = "Every day we see and meet people who look happy from the outside but deep down they are broken and are sad from the inside. For many people, money is the main cause of happiness or grief. But this is not right. Money can buy you food, luxurious house, healthy lifestyle servants, and many more facilities but money can’t buy you happiness."

In [ ]:

te.get_emotion(text)

{'Angry': 0.12, 'Fear': 0.42, 'Happy': 0.04, 'Sad': 0.33, 'Surprise': 0.08}

END OF TEXT TO EMOTION MODULE

In [216]:
df = pd.read_csv('https://query.data.world/s/bxqnpcoobelaq3lq4ry7cxffkb24hr')
df_test = pd.read_csv('https://raw.githubusercontent.com/vsrnitp/Emotion-Recognition-Dataset/main/test_text_emotion.csv')
df_val = pd.read_csv('https://raw.githubusercontent.com/vsrnitp/Emotion-Recognition-Dataset/main/val_text_emotion.csv')

In [217]:


df_test.head()

tweet_id  ...                                            content
0  1956967341  ...  @tiffanylue i know  i was listenin to bad habi...
1  1956967666  ...  Layin n bed with a headache  ughhhh...waitin o...
2  1956967696  ...                Funeral ceremony...gloomy friday...
3  1956967789  ...               wants to hang out with friends SOON!
4  1956968416  ...  @dannycastillo We want to trade with someone w...

[5 rows x 4 columns]

In [ ]:
df.drop(['tweet_id'], axis = 1) 

sentiment  ...                                            content
0           empty  ...  @tiffanylue i know  i was listenin to bad habi...
1         sadness  ...  Layin n bed with a headache  ughhhh...waitin o...
2         sadness  ...                Funeral ceremony...gloomy friday...
3      enthusiasm  ...               wants to hang out with friends SOON!
4         neutral  ...  @dannycastillo We want to trade with someone w...
...           ...  ...                                                ...
39995     neutral  ...                                   @JohnLloydTaylor
39996        love  ...                     Happy Mothers Day  All my love
39997        love  ...  Happy Mother's Day to all the mommies out ther...
39998   happiness  ...  @niariley WASSUP BEAUTIFUL!!! FOLLOW ME!!  PEE...
39999        love  ...  @mopedronin bullet train from tokyo    the gf ...

[40000 rows x 3 columns]

In [ ]:
df.drop(['author'], axis = 1) 

tweet_id  ...                                            content
0      1956967341  ...  @tiffanylue i know  i was listenin to bad habi...
1      1956967666  ...  Layin n bed with a headache  ughhhh...waitin o...
2      1956967696  ...                Funeral ceremony...gloomy friday...
3      1956967789  ...               wants to hang out with friends SOON!
4      1956968416  ...  @dannycastillo We want to trade with someone w...
...           ...  ...                                                ...
39995  1753918954  ...                                   @JohnLloydTaylor
39996  1753919001  ...                     Happy Mothers Day  All my love
39997  1753919005  ...  Happy Mother's Day to all the mommies out ther...
39998  1753919043  ...  @niariley WASSUP BEAUTIFUL!!! FOLLOW ME!!  PEE...
39999  1753919049  ...  @mopedronin bullet train from tokyo    the gf ...

[40000 rows x 3 columns]

In [219]:
del df['tweet_id']
del df_test['tweet_id']
del df_val['tweet_id']

In [220]:
df.head()

sentiment                                            content
0       empty  @tiffanylue i know  i was listenin to bad habi...
1     sadness  Layin n bed with a headache  ughhhh...waitin o...
2     sadness                Funeral ceremony...gloomy friday...
3  enthusiasm               wants to hang out with friends SOON!
4     neutral  @dannycastillo We want to trade with someone w...

In [221]:
def punctuation(val): 
  
    punctuations = '''()-[]{};:'"\,<>./@#$%^&_~'''
  
    for x in val.lower(): 
        if x in punctuations: 
            val = val.replace(x, " ") 
    return val

In [222]:
df.content = df.content.apply(lambda x : ' '.join(punctuation(emoji.demojize(x)).split()))
df_test.content = df_test.content.apply(lambda x : ' '.join(punctuation(emoji.demojize(x)).split()))
df_val.content = df_val.content.apply(lambda x : ' '.join(punctuation(emoji.demojize(x)).split()))

In [223]:
df_test.head()

sentiment                                            content
0       empty  tiffanylue i know i was listenin to bad habit ...
1     sadness  Layin n bed with a headache ughhhh waitin on y...
2     sadness                     Funeral ceremony gloomy friday
3  enthusiasm               wants to hang out with friends SOON!
4     neutral  dannycastillo We want to trade with someone wh...

In [224]:
df.info()
df_test.info()
df_val.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40000 entries, 0 to 39999
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype 
---  ------     --------------  ----- 
 0   sentiment  40000 non-null  object
 1   content    40000 non-null  object
dtypes: object(2)
memory usage: 625.1+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 499 entries, 0 to 498
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype 
---  ------     --------------  ----- 
 0   sentiment  499 non-null    object
 1   content    499 non-null    object
dtypes: object(2)
memory usage: 7.9+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 499 entries, 0 to 498
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype 
---  ------     --------------  ----- 
 0   sentiment  499 non-null    object
 1   content    499 non-null    object
dtypes: object(2)
memory usage: 7.9+ KB


In [225]:

# Splitting X and Y [aka statement and emotion] and getting the number of data that we have....
x_train = df.iloc[:,1] 
y_train = df.iloc[:,0] 

x_test = df_test.iloc[:,1] 
y_test = df_test.iloc[:,0] 

x_val = df_val.iloc[:,1] 
y_val = df_val.iloc[:,0] 

x_train,y_train = np.array(x_train),np.array(y_train)
x_test,y_test = np.array(x_test),np.array(y_test)
x_val,y_val = np.array(x_val),np.array(y_val)

print(x_train.shape,"|",y_train.shape)
print(x_test.shape,"|",y_test.shape)
print(x_val.shape,"|",y_val.shape)

#print(x_train[1])

(40000,) | (40000,)
(499,) | (499,)
(499,) | (499,)


In [226]:
int_y_train = []
int_y_test = []
int_y_val = []

for l in y_train:
    
    if l == "worry":        
        int_y_train.append(0)
        
    if l == "empty":       
        int_y_train.append(1)            
    if l == "happiness":      
        int_y_train.append(2)      
    if l == "surprise":
        int_y_train.append(3)
    if l == "boredom":
        int_y_train.append(4)
    if l == "neutral":
        int_y_train.append(5)
    if l == "anger":
        int_y_train.append(6)
    if l == "enthusiasm":
        int_y_train.append(7)
    if l == "fun":
        int_y_train.append(8)
    if l == "sadness":
        int_y_train.append(9)
    if l == "relief":
        int_y_train.append(10)
    if l == "love":
        int_y_train.append(11)
    if l == "hate":
        int_y_train.append(12)
    if l == "goat":
        int_y_val.append(13)
    if l == "bull":
        int_y_val.append(14)

for l in y_test:
    
    if l == "worry":        
        int_y_test.append(0)
        
    if l == "empty":       
        int_y_test.append(1)            
    if l == "happiness":      
        int_y_test.append(2)      
    if l == "surprise":
        int_y_test.append(3)
    if l == "boredom":
        int_y_test.append(4)
    if l == "neutral":
        int_y_test.append(5)
    if l == "anger":
        int_y_test.append(6)
    if l == "enthusiasm":
        int_y_test.append(7)
    if l == "fun":
        int_y_test.append(8)
    if l == "sadness":
        int_y_test.append(9)
    if l == "relief":
        int_y_test.append(10)
    if l == "love":
        int_y_test.append(11)
    if l == "hate":
        int_y_test.append(12)
    if l == "goat":
        int_y_val.append(13)
    if l == "bull":
        int_y_val.append(14)


for l in y_val:
    
    if l == "worry":        
        int_y_val.append(0)
        
    if l == "empty":       
        int_y_val.append(1)            
    if l == "happiness":      
        int_y_val.append(2)      
    if l == "surprise":
        int_y_val.append(3)
    if l == "boredom":
        int_y_val.append(4)
    if l == "neutral":
        int_y_val.append(5)
    if l == "anger":
        int_y_val.append(6)
    if l == "enthusiasm":
        int_y_val.append(7)
    if l == "fun":
        int_y_val.append(8)
    if l == "sadness":
        int_y_val.append(9)
    if l == "relief":
        int_y_val.append(10)
    if l == "love":
        int_y_val.append(11)
    if l == "hate":
        int_y_val.append(12)
    if l == "goat":
        int_y_val.append(13)
    if l == "bull":
        int_y_val.append(14)


int_y_train,int_y_test,int_y_val = np.array(int_y_train),np.array(int_y_test),np.array(int_y_val)
from sklearn import preprocessing
from keras.utils import np_utils

le = preprocessing.LabelEncoder()
le.fit(int_y_train)

encoded_y_train = le.transform(int_y_train)
encoded_y_test = le.transform(int_y_test)
encoded_y_val = le.transform(int_y_val)

encoded_y_train = np_utils.to_categorical(encoded_y_train)
encoded_y_test = np_utils.to_categorical(encoded_y_test)
encoded_y_val = np_utils.to_categorical(encoded_y_val)

#Here we are checking the emotions after getting encoded....
print(encoded_y_test)

#printing the label encoded value upto 10th row....
print(int_y_test[:20])

[[0. 1. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [1. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[ 1  9  9  7  5  0  9  0  9  9  5  0  9  9  3  9 11  9  0  9]


In [227]:
#importing nltk...
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [228]:
#Peforming Tokenization , padding and sequesting...
from tensorflow.python.keras.preprocessing.text import Tokenizer
from tensorflow.python.keras.preprocessing.sequence import pad_sequences
from nltk.corpus import stopwords

In [229]:
stopwords = stopwords.words('english')

x_train_cl = []
x_test_cl = []
x_val_cl = []

In [ ]:
unique_data=set(df.sentiment)
print(unique_data)

{'empty', 'happiness', 'enthusiasm', 'worry', 'boredom', 'fun', 'anger', 'sadness', 'surprise', 'hate', 'relief', 'neutral', 'love'}


In [ ]:
int_y_train[0]

1

In [230]:
# Deleting stopwords
for text in x_train:
    
    text = text.split()
    text = [word for word in text if word not in stopwords]
    text = " ".join(text)
    x_train_cl.append(text)
    
for text in x_test:
    
    text = text.split()
    text = [word for word in text if word not in stopwords]
    text = " ".join(text)
    x_test_cl.append(text)

for text in x_val:
    
    text = text.split()
    text = [word for word in text if word not in stopwords]
    text = " ".join(text)
    x_val_cl.append(text)
    
x_train,x_test,x_val = np.array(x_train_cl),np.array(x_test_cl),np.array(x_val_cl)

# We use total_text for fitting tokenizer in general 
total_text = np.concatenate((x_train,x_test,x_val),axis=0)

num_words = 2000

tokenizer = Tokenizer(num_words = num_words) 

tokenizer.fit_on_texts(total_text)

list(tokenizer.word_index)[:10]

['i', 'day', 'good', 'get', 'like', 'quot', 'go', 'http', 'work', 'today']

In [231]:
#Now we will tokenize everything.....
x_train_token = tokenizer.texts_to_sequences(x_train)
x_test_token = tokenizer.texts_to_sequences(x_test)
x_val_token = tokenizer.texts_to_sequences(x_val)

total_token = np.concatenate((x_train_token,x_test_token,x_val_token),axis=0)

<string>:6: VisibleDeprecationWarning:

Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray



In [232]:
# Padding (Getting the mean length of the text....)
print(np.mean([len(text) for text in total_token]))

6.48609688277477


In [236]:
#Using 26 as padding....
x_train_pad = pad_sequences(x_train_token,20) 
x_test_pad = pad_sequences(x_test_token,20)
x_val_pad = pad_sequences(x_val_token,20)

print(x_train_pad[0],end="\n-------------------------------------------------------------------------\n")


print(encoded_y_train[1])

[   0    0    0    0    0    0    0    0    0    0    0    0    0    0
   19   59  782  530 1097  469]
-------------------------------------------------------------------------
[0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]


**Model Building failed..... Trying another model.**